export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_ITEM_REQUEST = 'PRODUCT_ITEM_REQUEST';
export const PRODUCT_ITEM_SUCCESS = 'PRODUCT_ITEM_SUCCESS';
export const PRODUCT_ITEM_FAIL = 'PRODUCT_ITEM_FAIL';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';


export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_FAIL = 'USER_FAIL';



export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';

export const SETBACK ='SETBACK';

export const UPDATE_PASSWORD_REQUEST ='UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS ='UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL ='UPDATE_PASSWORD_FAIL';