export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_ITEM_REQUEST = 'PRODUCT_ITEM_REQUEST';
export const PRODUCT_ITEM_SUCCESS = 'PRODUCT_ITEM_SUCCESS';
export const PRODUCT_ITEM_FAIL = 'PRODUCT_ITEM_FAIL';
export const PRODUCT_ITEM_RESET = 'PRODUCT_ITEM_RESET';

export const ADD_CART_ITEM_REQUSET = 'ADD_CART_ITEM_REQUSET';
export const ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS';
export const ADD_CART_ITEM_FAIL = 'ADD_CART_ITEM_FAIL';
export const ADD_CART_ITEM_RESET = 'ADD_CART_ITEM_RESET';

export const GET_CART_ITEM_REQUSET = 'GET_CART_ITEM_REQUSET';
export const GET_CART_ITEM_SUCCESS = 'GET_CART_ITEM_SUCCESS';
export const GET_CART_ITEM_FAIL = 'GET_CART_ITEM_FAIL';

export const REMOVE_CART_ITEM_REQUSET = 'REMOVE_CART_ITEM_REQUSET';
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';
export const REMOVE_CART_ITEM_FAIL = 'REMOVE_CART_ITEM_FAIL';
export const REMOVE_CART_ITEM_RESET = 'REMOVE_CART_ITEM_RESET';


export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_FAIL = 'USER_FAIL';



export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';

export const SETBACK ='SETBACK';

export const UPDATE_PASSWORD_REQUEST ='UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS ='UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL ='UPDATE_PASSWORD_FAIL';


export const ADD_TO_ORDER_ITEM = 'ADD_TO_ORDER_ITEM';
export const ADD_SHIPPING_ADDRESS = 'ADD_SHIPPING_ADDRESS'; 
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';

export const GET_SHIPPING_REQUEST = 'GET_SHIPPING_REQUEST';
export const GET_SHIPPING_SUCCESS = 'GET_SHIPPING_SUCCESS';
export const GET_SHIPPING_FAIL = 'GET_SHIPPING_FAIL';


export const PLACEORDER_REQUEST = 'PLACEORDER_REQUEST';
export const PLACEORDER_SUCCESS = 'PLACEORDER_SUCCESS';
export const PLACEORDER_FAIL = 'PLACEORDER_FAIL';

export const GETORDERBYID_REQUEST = 'GETORDERBYID_REQUEST';
export const GETORDERBYID_SUCCESS = 'GETORDERBYID_SUCCESS';
export const GETORDERBYID_FAIL = 'GETORDERBYID_FAIL';
export const GETORDERBYID_RESET = 'GETORDERBYID_RESET';

export const GET_ALL_ORDER_REQUEST = 'GET_ALL_ORDER_REQUEST';
export const GET_ALL_ORDER_SUCCESS = 'GET_ALL_ORDER_SUCCESS';
export const GET_ALL_ORDER_FAIL = 'GET_ALL_ORDER_FAIL';


export const ORDERPAY_REQUEST = 'ORDERPAY_REQUEST';
export const ORDERPAY_SUCCESS = 'ORDERPAY_SUCCESS';
export const ORDERPAY_FAIL = 'ORDERPAY_FAIL';
export const ORDERPAY_RESET = 'ORDERPAY_RESET';
export const RESET_ORDER ='RESET_ORDER ';

export const ADMIN_USER_REQUEST = 'ADMIN_USER_REQUEST';
export const ADMIN_USER_SUCCESS = 'ADMIN_USER_SUCCESS';
export const ADMIN_USER_FAIL = 'ADMIN_USER_FAIL';
export const ADMIN_USER_RESET = 'ADMIN_USER_RESET';
export const ADMIN_USER_DELETE_REQUEST = 'ADMIN_USER_DELETE_REQUEST';
export const ADMIN_USER_DELETE_SUCCESS = 'ADMIN_USER_DELETE_SUCCESS';
export const ADMIN_USER_DELETE_FAIL = 'ADMIN_USER_DELETE_FAIL';

export const ADMIN_USER_GET_REQUEST = 'ADMIN_USER_GET_REQUEST';
export const ADMIN_USER_GET_SUCCESS = 'ADMIN_USER_GET_SUCCESS';
export const ADMIN_USER_GET_FAIL = 'ADMIN_USER_GET_FAIL';
export const ADMIN_RESET_GET_USER = 'ADMIN_RESET_GET_USER'

export const ADMIN_USER_UPADTE_REQUEST ='ADMIN_USER_UPADTE_REQUEST';
export const ADMIN_USER_UPADTE_SUCCESS ='ADMIN_USER_UPADTE_SUCCESS';
export const ADMIN_USER_UPADTE_FAIL ='ADMIN_USER_UPADTE_FAIL';
export const RESET_ADMIN ='RESET_ADMIN'

export const ADMIN_EDIT_PRODUCT_REQUEST ='ADMIN_EDIT_PRODUCT_REQUEST';
export const ADMIN_EDIT_PRODUCT_SUCCESS ='ADMIN_EDIT_PRODUCT_SUCCESS';
export const ADMIN_EDIT_PRODUCT_FAIL ='ADMIN_EDIT_PRODUCT_FAIL';
export const ADMIN_EDIT_PRODUCT_RESET ='ADMIN_EDIT_PRODUCT_RESET';

export const ADMIN_UPLOAD_PHOTO_REQUEST ='ADMIN_UPLOAD_PHOTO_REQUEST';
export const ADMIN_UPLOAD_PHOTO_SUCCESS ='ADMIN_UPLOAD_PHOTO_SUCCESS';
export const ADMIN_UPLOAD_PHOTO_FAIL ='ADMIN_UPLOAD_PHOTO_FAIL';
export const ADMIN_UPLOAD_PHOTO_RESET ='ADMIN_UPLOAD_PHOTO_RESET';

export const DELIVER_REQUEST = 'DELIVER_REQUEST';
export const DELIVER_SUCCESS = 'DELIVER_SUCCESS'
export const DELIVER_FAIL = 'DELIVER_FAIL'
export const DELIVER_RESET = 'DELIVRESETEST'